name: Validate JSON

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate JSON
        id: validate_json
        uses: docker://orrosenblatt/validate-json-action:latest
        env:
          INPUT_SCHEMA: schema.json
          INPUT_JSONS: contact-points.json
      - name: Report validation failure
        if: failure()
        run: echo "JSON validation failed. Invalid files: ${{ steps.validate_json.outputs.invalid }}"