name: Validate JSON files

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate-json:
    name: Validate JSON files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Find and validate JSON files
        run: |
          set -euo pipefail
          echo "Searching for .json files (excluding node_modules, build, dist, .git)"
          failed=0

          # Null-delimited find to handle arbitrary filenames safely
          while IFS= read -r -d '' file; do
            echo "Checking $file"
            if ! python -m json.tool "$file" 2>err; then
              # GitHub annotation so the file and error show up in the run UI
              echo "::error file=$file::Invalid JSON in $file"
              echo "----- parse error for $file -----"
              cat err
              echo "---------------------------------"
              failed=1
            fi
          done < <(find . -type f -name '*.json' \
            -not -path './node_modules/*' \
            -not -path './build/*' \
            -not -path './dist/*' \
            -not -path './.git/*' -print0)

          if [ "$failed" -ne 0 ]; then
            echo "One or more JSON files failed validation."
            exit 1
          fi

          echo "All JSON files are valid."
