# .github/workflows/validate-json.yml

name: Validate JSON files

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate-json:
    name: Validate JSON files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Find and validate JSON files
        run: |
          set -euo pipefail
          failed=0
          while IFS= read -r -d '' file; do
            echo "Checking $file"
            if ! python -m json.tool "$file" >/dev/null 2>err; then
              echo "::error file=$file::Invalid JSON in $file"
              cat err
              failed=1
            fi
          done < <(find . -type f -name '*.json' \
            -not -path './node_modules/*' \
            -not -path './build/*' \
            -not -path './dist/*' \
            -not -path './.git/*' -print0)

          if [ "$failed" -ne 0 ]; then
            echo "One or more JSON files failed validation."
            exit 1
          fi

          echo "All JSON files are valid."
